### ISSUE TITLE
'### Heading' expected for '<h3>Heading</h3>', but get '**Heading**'

### ISSUE THREAD

**Issue by mehrvarz** [JohannesKaufmann/html-to-markdown#103]
HTML input `<h3>Heading</h3>` should generate `### Heading.` And it usually does.

But sometimes I see `**Heading**` being generated instead. What could be causing this?

**Comment by JohannesKaufmann** [comment]
@mehrvarz can you post a reproducible example?

---

Are these headings inside links? If yes, here is reason:

> If you want a heading inside a link, that does not work. While the # heading is a block element, the \[link](href) is an inline element. And it is invalid to have block elements inside inline elements.
> https://html-to-markdown.com/docs/heading-in-link

The best alternative is rendering the heading as bold text instead ([see source](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/commonmark.go#L136-L141)).

**Comment by mehrvarz** [comment]
Thank you for your response. There are two anchor elements right in front of the `<h3>` element. But they are closed. Can they still influence the `<h3>` element in such a way? (I have added some newlines to this 3rd party HTML for clarity:)

```
<body style="background-color: #ffffff;">
<div>
<a id="d15e12847"/>
<a id="navpoint.d15e11188"/>
<h3 class="p_l-h3">Header text</h3>
```

**Comment by JohannesKaufmann** [comment]
You can try to [Parse](https://pkg.go.dev/golang.org/x/net/html#example-Parse) and then [Render](https://pkg.go.dev/golang.org/x/net/html#Render) your snippet using the "golang.org/x/net/html" package.

It is very likely that the `h3` tag actually ends up _inside_ the `a` tag. The `a` tag cannot usually be *self-closing* in html5...

<img width="529" alt="Screenshot 2024-06-29 at 19 31 43" src="https://github.com/JohannesKaufmann/html-to-markdown/assets/20886667/c2aee37c-020d-4344-8d4e-37f8a19c7d27">

**Comment by mehrvarz** [comment]
Holla! I can fix the issue by dynamically converting all `<a id="..."/>` to `<a id="..."></a>` in a preprocessing step. Feels a little expensive, but it may be cheaper than a full Parse and Render. Need to think about it...
Ideally, your code would act differently based on xmlns. Right?
For now, I can live with this. Thank you very much!

```
// convert "<a .../>" to "<a ...></a>"
idxAll := 0
idxAnchor := strings.Index(htmlStr,"<a ")
for idxAnchor>=0 {
	idxAll = idxAll + idxAnchor
	idxCloseAnchor := strings.Index(htmlStr[idxAll+3:],">")
	if idxCloseAnchor>=0 {
		idxAll = idxAll + 3 + idxCloseAnchor
		if htmlStr[idxAll+3+idxCloseAnchor-1] == '/' {
			htmlStr = htmlStr[:idxAll+3+idxCloseAnchor-1] + "></a>" +
				htmlStr[idxAll+3+idxCloseAnchor+1:]
			idxAll = idxAll + 3
		}
	}
	idxAnchor = strings.Index(htmlStr[idxAll:],"<a ")
}
```
