### ISSUE TITLE
[Request]Binary releases

### ISSUE THREAD

**Issue by samveen** [JohannesKaufmann/html-to-markdown#107]
Is it possible to get binary releases (maybe via GH-actions), as the CI already creates builds as part of the testing mechanism?

**Comment by JohannesKaufmann** [comment]
@samveen what exactly are you trying to achieve? How would you like to use it?

There is also a [CLI](https://github.com/JohannesKaufmann/html-to-markdown?tab=readme-ov-file#using-it-on-the-command-line) available if that helps...

**Comment by samveen** [comment]
@JohannesKaufmann As per the existing installation instuctions, deploying the binary is as below:

```
go get github.com/JohannesKaufmann/html-to-markdown
```

The above instructions expect the availability of `golang` , and the expectation that the binary will be build locally on the client machine.

The CI process builds the binary as per `.github/workflows/go.yml`. 

What I'm hoping is that as part of the release process, the binary created by the CI process be attached to the newly created release, so that users do not need to have `golang` installed on their workstations , and can instead download the pre-build binary from the releases page of this project.
