### ISSUE TITLE
html <br> not suport.

### ISSUE THREAD

**Issue by kingreatwill** [JohannesKaufmann/html-to-markdown#11]
```
var html =`
<p>1. xxx <br/>2. xxxx<br/>3. xxx</p><p><span class="img-wrap"><img src="xxx"></span><br>4. golang<br>a. xx<br>b. xx</p>
`

func Test_md(t *testing.T) {
	var converter = md.NewConverter("", true, nil)
	md_str,_ := converter.ConvertString(html)
	println(md_str)
}
```
output
```
1\. xxx 2\. xxxx3\. xxx

![](xxx)4\. golanga. xxb. xx
```
want
```
1. xxx 
2. xxxx
3. xxx

![](xxx)
4. golang
a. xx
b. xx
```

**Comment by JohannesKaufmann** [comment]
@kingreatwill yeah true, thats still missing. Thanks for reporting. I will add that on the weekend.

----

For now, you can add a new rule for yourself. See [examples/add_rule](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/examples/add_rules/main.go). 

Something like that (although I haven't tested it yet):

```
	newline := md.Rule{
		Filter: []string{"br"}, // register <br>
		Replacement: func(content string, selec *goquery.Selection, opt *md.Options) *string {
			return md.String("\n\n") // return markdown
		},
	}

	conv := md.NewConverter("", true, nil)
	conv.AddRules(newline)
```

**Comment by kingreatwill** [comment]
Thank you!  " \."  How to deal with it.

**Comment by JohannesKaufmann** [comment]
The escape character ("\\") is done because otherwise there would be many side effects from characters that are falsely interpreted as markdown. See [issue 7](https://github.com/JohannesKaufmann/html-to-markdown/issues/7#issuecomment-602811869). Thats why the library is escaping any "markdown like" content inside the original HTML content so that final markdown is valid.

_But I'm thinking about providing an option to disable that as many don't like it 🤷‍♂️_

----

But the escaping does no harm to how its rendered. It basically just disables the markdown:

**(with escaping)**
```
1\. xxx
2\. xxxx
3\. xxx

![](xxx)
4\. golang
a. xx
b. xx
```

1\. xxx
2\. xxxx
3\. xxx

![](xxx)
4\. golang
a. xx
b. xx

-----

**(without escaping)**
```
1. xxx
2. xxxx
3. xxx

![](xxx)
4. golang
a. xx
b. xx
```

1. xxx
2. xxxx
3. xxx

![](xxx)
4. golang
a. xx
b. xx

**Comment by kingreatwill** [comment]
var html =`jmap –histo[:live]`
out
```
jmap –histo\$&:live\$&
```
How to keep it as it is?

**Comment by kingreatwill** [comment]
> The escape character ("\") is done because otherwise there would be many side effects from characters that are falsely interpreted as markdown. See [issue 7](https://github.com/JohannesKaufmann/html-to-markdown/issues/7#issuecomment-602811869). Thats why the library is escaping any "markdown like" content inside the original HTML content so that final markdown is valid.
> 
> _But I'm thinking about providing an option to disable that as many don't like it 🤷‍♂️_
> 
> But the escaping does no harm to how its rendered. It basically just disables the markdown:
> 
> **(with escaping)**
> 
> ```
> 1\. xxx
> 2\. xxxx
> 3\. xxx
> 
> ![](xxx)
> 4\. golang
> a. xx
> b. xx
> ```
> 
> 1. xxx
> 2. xxxx
> 3. xxx
> 
> ![](xxx)
> 4. golang
> a. xx
> b. xx
> 
> **(without escaping)**
> 
> ```
> 1. xxx
> 2. xxxx
> 3. xxx
> 
> ![](xxx)
> 4. golang
> a. xx
> b. xx
> ```
> 
> 1. xxx
> 2. xxxx
> 3. xxx
> 
> ![](xxx)
> 4. golang
> a. xx
> b. xx

Thank you!

**Comment by kingreatwill** [comment]
Thank you!

**Comment by JohannesKaufmann** [comment]
I just merged the changes. You should be able to update the library with `go get -u github.com/JohannesKaufmann/html-to-markdown`

1. `<br>` should now be parsed without any extra rules
2. the escaping for links ("[" and "]") was disabled and a test case was added

@kingreatwill please let me know if you find any other HTML snippets that don't output the correct result!

**Comment by kingreatwill** [comment]
Thank you very much!
