### ISSUE TITLE
🐛 Bug

### ISSUE THREAD

**Issue by dvogt23** [JohannesKaufmann/html-to-markdown#110]
**Describe the bug**
Eating a space between a link and a mention from mastodon post.

**HTML Input**
```html
<p>test this archive project 🤩 <a href=\"https://mas.to/tags/microblog\" class=\"mention hashtag\" rel=\"tag\">#<span>microblog</span></a> <span class=\"h-card\" translate=\"no\"><a href=\"https://social.coop/@ggpsv\" class=\"u-url mention\">@<span>ggpsv</span></a></span></p>
```

**Generated Markdown**
````markdown
test this archive project 🤩 [#microblog](\"https://mas.to/tags/microblog\")[@ggpsv](\"https://social.coop/@ggpsv\")
````

**Expected Markdown**
````markdown
test this archive project 🤩 [#microblog](\"https://mas.to/tags/microblog\") [@ggpsv](\"https://social.coop/@ggpsv\")
````

Tested with html2md on cli with actual version.

**Comment by JohannesKaufmann** [comment]
Hi @dvogt23 

thanks for submitting the bug! This is similar to #95 and will be fixed with V2 of the libary ([see demo](https://html-to-markdown.com/demo)).

**Comment by JohannesKaufmann** [comment]
On the ["v2" branch](https://github.com/JohannesKaufmann/html-to-markdown/tree/v2) are a lot of improvements — including a fix to this bug. 

It is still experimental but feel free to give it a try. Happy to hear about your experience 😊

I am going to close this issue. If you find anything with the new version, please open a new issue!
