### ISSUE TITLE
Output of go list -m -versions?

### ISSUE THREAD

**Issue by for-coursera** [JohannesKaufmann/html-to-markdown#115]
Sorry if I'm missing something but why 

    go list -m -versions github.com/JohannesKaufmann/html-to-markdown

doesn't list the 2.x versions? This is the output:

    github.com/JohannesKaufmann/html-to-markdown v1.0.0 v1.1.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.3.2 v1.3.3 v1.3.4 v1.3.5 v1.3.6 v1.3.7 v1.4.0 v1.4.1 v1.4.2 v1.5.0 v1.6.0

**Comment by JohannesKaufmann** [comment]
@for-coursera Try it with the `/v2` suffix:

```
go list -m -versions github.com/JohannesKaufmann/html-to-markdown/v2
```

**Comment by for-coursera** [comment]
@JohannesKaufmann 

Thanks, that works!

Sorry, I don't know Go at all, could you please guide me a little bit more? I'm trying to build https://github.com/suntong/html2md project with your new version (if that's possible at all). So, I edit their go.mod and replace:

    github.com/JohannesKaufmann/html-to-markdown v1.6.0

with:

    github.com/JohannesKaufmann/html-to-markdown/v2 v2.1.0

And then run `go mod tidy`. Which changes it back to v1.6.0.

Could you maybe tell me what am I doing wrong? :)

**Comment by JohannesKaufmann** [comment]
There is a v2 version because there are breaking changes. The v2 also has a completely new api — however not every functionality is already implemented.
So just switching the imports will unfortunately not work.

What exactly are you using the CLI for?

There is now also a [CLI included](https://github.com/JohannesKaufmann/html-to-markdown#cli---using-it-on-the-command-line) by default. Have you tried that already?

**Comment by for-coursera** [comment]
@JohannesKaufmann 

Thanks again! Got it :)

As per your question, off the top of my head, the included CLI doesn't seem to support CSS/goquery selectors (like, only converting the specified selectors, or, on the contrary, excluding ones), which [html2md](https://github.com/suntong/html2md) can. But maybe I'm wrong :)

**Comment by JohannesKaufmann** [comment]
Okay, that's a good point. That would be a good feature 👍

**Comment by for-coursera** [comment]
@JohannesKaufmann 

Further to our discussion -- and especially further to your hint on possible future features :) --  please, note that [due to upstream issues](https://github.com/suntong/html2md/issues/21), the [html2md repository](https://github.com/suntong/html2md/) has just been archived. 

Thus, probably indeed a good time to maybe borrow some their [features](https://github.com/suntong/html2md/?tab=readme-ov-file#usage) for your CLI?

**Comment by for-coursera** [comment]
@JohannesKaufmann, thanks!
