### ISSUE TITLE
How to get running with this, new to Go

### ISSUE THREAD

**Issue by samjones3** [JohannesKaufmann/html-to-markdown#116]
I am new to Go, on Windows. (fair amount of python and powershell experience)

I have a Go hello world working, but when I try to build or run the pieces I pulled from github I get nowhere.

I did this:
git pull .... // got the github kit
installed go

Where do I go from here?

(Sorry for the noob question! Want to get into this!)

**Comment by JohannesKaufmann** [comment]
@samjones3 Great that you are learning Golang! 🚀 

- At first, try to learn the basics with the [Go Tour](https://go.dev/tour/).
- Once you know the basics: Create a folder on your computer, place a `main.go` file there and run `go mod init`
- Then you can copy & paste on of the [examples from this repo](https://github.com/JohannesKaufmann/html-to-markdown/blob/main/examples/basics/main.go) into your own `main.go` file.
- Install the package by running `go get -u github.com/JohannesKaufmann/html-to-markdown/v2`
- Then run your own program with `go run main.go`


Let me know it you have any questions!
