### ISSUE TITLE
[Feature]: Render an <a> tag with empty href as a normal text

### ISSUE THREAD

**Issue by rkuska** [JohannesKaufmann/html-to-markdown#120]
### Describe the improvement

Currently when an element like `<a href="">Activities</a></li>` is encountered the node is rendered as [Activities](). I would just  prefer to have `Activities`.

Is there an option to enable such behavior? 

(This is the default behavior of python's markdownify)

**Comment by JohannesKaufmann** [comment]
@rkuska you spotted some difficult topics 😅




> 1) Render an <a> tag with empty href as a normal text

I try to keep very close to Commonmark. As such, I decided to keep the link for an empty href (by *default*). 

> 2) missing a content [...] render the link still

That seems to be what Commonmark does. So I am probably going to make this the *default*...

<img width="911" alt="Screenshot 2024-11-21 at 21 44 17" src="https://github.com/user-attachments/assets/e44f9252-71d9-4113-851e-4566d3745c20">

[commonmark demo](https://spec.commonmark.org/dingus/?text=%0A%0A1.%20before%20%5Bno%20link%5D()%20after%0A%0A2.%20before%20%5B%5D(%2Fno_content)%20after%0A)

---

That being said, I am open to make this configurable!
@rkuska Do you have any naming in mind?

**Comment by JohannesKaufmann** [comment]
Thanks @rkuska for creating the issue!

There are now two new configuration options for the commonmark package. Here are the defaults:

- `WithLinkEmptyHrefBehavior(LinkBehaviorRender)`
- `WithLinkEmptyContentBehavior(LinkBehaviorRender)`

But they can also be configured to **skip the rendering as a link** with `LinkBehaviorSkip`.
