### ISSUE TITLE
[Feature]: Instruction how to build CLI from source

### ISSUE THREAD

**Issue by jcubic** [JohannesKaufmann/html-to-markdown#123]
### Describe the improvement

There is an issue to add Distributions for other system:

* https://github.com/JohannesKaufmann/html-to-markdown/issues/119

But there is a chance that some distro will not have a package, and make take a long time to create distributions.

Why not add instructions how to compile/build CLI yourself. I don't know Golang, so I have no idea how to create an executable. On Linux, you often use Makefile to build a project.

**Comment by JohannesKaufmann** [comment]
There are binaries available for multiple platforms and architectures on the [releases page](https://github.com/JohannesKaufmann/html-to-markdown/releases).

If your combination is not available you can also build from source. Added information about that to the README.

To build locally (requires Go):

```bash
go build -o html2markdown ./cli
```
