### ISSUE TITLE
[Feature]: Installation Results in Non-Descriptive Binary Name `cli`

### ISSUE THREAD

**Issue by kpym** [JohannesKaufmann/html-to-markdown#125]
## Description
Currently, when installing the CLI using the following command:

```sh
go install github.com/JohannesKaufmann/html-to-markdown/v2/cli@latest
```

The resulting binary is named `cli`. This name is generic and not descriptive, potentially causing confusion when multiple binaries are installed in the same environment.

## Steps to Reproduce
1. Run the command:
   ```sh
   go install github.com/JohannesKaufmann/html-to-markdown/v2/cli@latest
   ```
2. Check the resulting binary name in your `$GOBIN` or `$GOPATH/bin` directory:
   ```sh
   ls $GOBIN
   ```
3. Observe that the binary is named `cli`.

## Proposed Solution
Move the `cli` folder to `cli/html2md` so that the installation command becomes:  

```sh
go install github.com/JohannesKaufmann/html-to-markdown/v2/cli/html2md@latest
```

This change would result in the binary being named `html2md`, which is more descriptive and aligns with the tool's functionality.  

## Benefits
- Avoids naming conflicts with other tools that might use a generic name like `cli`.
- Improves clarity for users who rely on the binary name to identify its purpose.

Let me know if further clarification is needed or if additional input would help refine the proposal.

**Comment by JohannesKaufmann** [comment]
@kpym good idea!

Moved the `cli` folder to `cli/html2markdown`

**Comment by kpym** [comment]
@JohannesKaufmann Thank you for addressing my suggestion and for moving the CLI folder to <code>cli/html2markdown</code>.

To further streamline the setup process for users, I recommend adding the following command to the <a href="https://github.com/JohannesKaufmann/html-to-markdown?tab=readme-ov-file#build-from-source">Build from Source</a> section of the README:

<pre><code>go install github.com/JohannesKaufmann/html-to-markdown/v2/cli/html2md@latest</code></pre>

This command provides a quick and standard way to install the CLI tool using Go, which might reduce friction for users unfamiliar with manual builds or repository structure. Including it would align with common practices in Go projects and enhance usability.

Thank you again for your work on this project!

**Comment by JohannesKaufmann** [comment]
Added the section to the README. 

All the changes are now part of the new release. So the install should now work. Please let me know if you notice any problems...
