### ISSUE TITLE
go get unable to handle certain filenames

### ISSUE THREAD

**Issue by meooow25** [JohannesKaufmann/html-to-markdown#17]
Hello,

Thank you for this library.
However I am unable to use the latest version.
```
$ go get github.com/JohannesKaufmann/html-to-markdown@master
verifying github.com/JohannesKaufmann/html-to-markdown@v0.0.0-20200401123428-60f6dc365f89/go.mod: github.com/JohannesKaufmann/html-to-markdown@v0.0.0-20200401123428-60f6dc365f89/go.mod: reading https://sum.golang.org/lookup/github.com/!johannes!kaufmann/html-to-markdown@v0.0.0-20200401123428-60f6dc365f89: 410 Gone
```

Visiting the [sum.golang.org link](https://sum.golang.org/lookup/github.com/!johannes!kaufmann/html-to-markdown@v0.0.0-20200401123428-60f6dc365f89) in the error
```
not found: create zip: malformed file path "testdata/TestFromString/<br>_adds_new_line_break.golden": invalid char '<'
```

Would you please consider updating the file names so that the issue is resolved?
Thanks

**Comment by JohannesKaufmann** [comment]
@meooow25 sorry for that 🙈. Should be fixed now, let me know if it still doesn't work.

`go get -u github.com/JohannesKaufmann/html-to-markdown`
