### ISSUE TITLE
Mention wrapper program in README.md?

### ISSUE THREAD

**Issue by suntong** [JohannesKaufmann/html-to-markdown#21]
Hi @JohannesKaufmann 

I love your project so much that I added a wrapper program to it:

```sh
$ html2md -i https://github.com/suntong/lang
[Homepage](https://github.com/)
. . . 


$ html2md -i https://github.com/suntong/lang -s 'div#readme'   
## README.md

# lang -- programming languages demos
```

Would it be OK that I PR to README.md to mention `html2md` when it is ready? So far I'm having these planned out:

```sh
$ html2md
HTML to Markdown
Version 0.1.0 built on 2020-07-26
Copyright (C) 2020, Tong Sun

HTML to Markdown converter on command line

Usage:
  html2md [Options...]

Options:

  -h, --help                       display help information 
  -i, --in                        *The html/xml file to read from (or stdin) 
  -d, --domain                     Domain of the web page, needed for links when --in is not url 
  -s, --sel                        CSS/goquery selectors [=body]
  -v, --verbose                    Verbose mode (Multiple -v options increase the verbosity.) 

      --opt-heading-style          Option HeadingStyle 
      --opt-horizontal-rule        Option HorizontalRule 
      --opt-bullet-list-marker     Option BulletListMarker 
      --opt-code-block-style       Option CodeBlockStyle 
      --opt-fence                  Option Fence 
      --opt-em-delimiter           Option EmDelimiter 
      --opt-strong-delimiter       Option StrongDelimiter 
      --opt-link-style             Option LinkStyle 
      --opt-link-reference-style   Option LinkReferenceStyle 

  -A, --plugin-conf-attachment     Plugin ConfluenceAttachments 
  -C, --plugin-conf-code           Plugin ConfluenceCodeBlock 
  -F, --plugin-frontmatter         Plugin FrontMatter 
  -G, --plugin-gfm                 Plugin GitHubFlavored 
  -S, --plugin-strikethrough       Plugin Strikethrough 
  -T, --plugin-table               Plugin Table 
  -L, --plugin-task-list           Plugin TaskListItems 
  -V, --plugin-vimeo               Plugin VimeoEmbed 
  -Y, --plugin-youtube             Plugin YoutubeEmbed 
```

Thanks

**Comment by suntong** [comment]
First round done:

```sh
$ echo '<strong>Bold Text</strong>' | html2md -i
**Bold Text**

$ echo '<strong>Bold Text</strong>' | html2md -i --opt-strong-delimiter="__"
__Bold Text__


$ echo '<ul><li><input type=checkbox checked>Checked!</li><li><input type=checkbox>Check Me!</li></ul>' | html2md -i -G
- [x] Checked!
- [ ] Check Me!
```

**Comment by JohannesKaufmann** [comment]
@suntong looks cool 🎉. You can, of course, create a PR once it's nearly finished. I will then test the CLI a bit before merging.

That also means we should communicate when mayor bug fixes are done. I would say that my library is stable, as in all changes are backwards compatible. But there are still many edge cases that I'm finding and that means many commits. But I will introduce versioning soon.

**Comment by suntong** [comment]
It's done now. Sorry I should have mentioned it's location, it's the newest project under my github  -- https://github.com/suntong/html2md. Only the output of https://github.com/suntong/html2md#using-goquery is missing, which will be there once #22 is fixed. Please take a look, and give me some feedbacks. thanks

**Comment by JohannesKaufmann** [comment]
@suntong just wanted to let you know that I'm quite busy in the next couple of days. But I haven't forgotten it and will take care of it sometime next week.

**Comment by JohannesKaufmann** [comment]
@suntong I had a look at it and it seems to be working quite well 💯

The recent changes:
- the `Table` Plugin is not experimental anymore
- there is now a new plugin called `TableCompat` for environments where tables are not supported
- I had to rename the experimental plugins from `EXPERIMENTAL_Xxx` to `EXPERIMENTALXxx` (without the underscore, to make the linter happy)

**Comment by suntong** [comment]
Thanks for the review & udpates and all the previous fixes, Johannes.

My `html2md` is now updated. See https://github.com/suntong/html2md#testing-the-new-table-plugins

I've also submitted a PR to close this. Please review. 

thanks

**Comment by JohannesKaufmann** [comment]
@suntong I just merged your PR. Thanks alot for your work on the CLi 🎉

**Comment by suntong** [comment]
Oh, thanks for that, and most importantly thanks for the html-to-markdown library. This is something that I had been searching over and over throughout the years for several years now -- very glad you are providing it now. 

It has been a pleasant experience working with you -- I had been hoping that you tag a release version, but before I asked for it officially, you've already did it. I've start the process of package it into the official Debian repository -- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968146. There are a few dependencies that need to be dealt with first, but we will be there... 

cheers
