### ISSUE TITLE
Proper spaces missing

### ISSUE THREAD

**Issue by suntong** [JohannesKaufmann/html-to-markdown#23]
Check out the outputs from #21 & #22:

```md
Only ~blue ones~~left~

[go](/topics/go "Topic: go")[golang](/topics/golang "Topic: golang")[html](/topics/html "Topic: html")[html-to-markdown](/topics/html-to-markdown "Topic: html-to-markdown")[markdown](/topics/markdown "Topic: markdown")
```

I think proper spaces are missing between items (between "ones" and "left", and between all the tags)

**Comment by JohannesKaufmann** [comment]
@suntong this should now be fixed in the latest version.

Make sure to update the library by running:
```
go get -u github.com/JohannesKaufmann/html-to-markdown
```

If you encounter any other bugs, feel free to open a new issue...
