### ISSUE TITLE
Provide a cmd package

### ISSUE THREAD

**Issue by qlcom** [JohannesKaufmann/html-to-markdown#27]

**Comment by JohannesKaufmann** [comment]
@qlcom someone wrote [html2md](https://github.com/suntong/html2md#usage) which is a cli that you can use for now. Does that fit your needs?

**Comment by qlcom** [comment]
> Does that fit your needs?

No. That cli isn't well designed. And the code isn't good.

**Comment by qlcom** [comment]
writing a cmd package yourself will not take a long time.

**Comment by JohannesKaufmann** [comment]
Sure, I could create a cli. The problem is, that I'm not sure how people would use it. And I don't want to make breaking changes latter.

@qlcom can you provide your use-case? How would you want to use it? What features would you need? What should be done better than html2md?

**Comment by qlcom** [comment]
i am not sure. I want things that are simple and well designed.
