### ISSUE TITLE
Option/Flag to completely modify before-after hooks

### ISSUE THREAD

**Issue by dandynaufaldi** [JohannesKaufmann/html-to-markdown#28]
First, thanks for the great library
I was wondering whether we may have a way to enable overwrite/toggle the before-after hooks.
My current use-case don't want multiple newlines to be removed like the default [before hook](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/from.go#L113)
Thanks

**Comment by JohannesKaufmann** [comment]
Yeah you are totally right. I have just added `conv.ClearBefore()` and `conv.ClearAfter()` to clear the hooks. Let me know if that is not working.


Just out of curiosity, why don't you want multiple newlines to be removed? Can you share the use-case? 

---


⚠️ But, beware of upgrading. 

Once I have some free time 🙈, the way that escaping is currently done needs to be rewritten. I have thought of a good way _(see below)_ that should be a lot more reliable. It's going to be backwards compatible and not noticeable from the outside. Except if you clear the default before/hooks 🤷‍♂️


_How the escaping is supposed to work: First step is to escape all markdown characters inside the HTML. Then the converting is done. Lastly, the "after" hooks goes through the generated markdown and unescape (removing the "\\" sign) where it's not necessary anymore._ 

That means that you are going to see a lot of escape characters without the hook. But you will be able to manually enable the hook again.

✉️ I will let you know when/if the change is happening...

**Comment by dandynaufaldi** [comment]
great, thanks for the update
