### ISSUE TITLE
Usage of IsInlineElement function

### ISSUE THREAD

**Issue by dandynaufaldi** [JohannesKaufmann/html-to-markdown#29]
So, per my observation `multipleNewLinesRegex` was used because we may encounter excessive newline as a result of consecutive inline element, as we add newline before and after its content (in some elements).
Could we use IsInlineElement function to only add the required newline?
For example if we encounter an inline element and the previous sibling isn't an inline element, then we may add newline as prefix

**Comment by JohannesKaufmann** [comment]
@dandynaufaldi  Could you share why `multipleNewLinesRegex` is troubbling you? Then I can add test cases for that.


Newlines are added all over the place, for many **block elements** (p, div, h1-6, pre, br, ...). If I remember correctly `multipleNewLinesRegex` is used to make the final markdown nicer, but also for making sure that a blockquote is not split up.

With **inline elements** I have started to be a bit more direct (see `AddSpaceIfNessesary`). That function seems to be similar to what you are proposing...



In general I have been trying to replace regex with custom functions operating on the string itself. But that is alot of work and tricky 🤷‍♂️



Feel free to try it out and submit a PR. There is a very extensive test suite. As long as the "golden file tests" don't change drastically, it is very safe to change things. You can run those tests with `--update` and then the files in the `testdata` folder will be updated (and should be checked into git).
