### ISSUE TITLE
🐛 `&lt;` and `&gt;` should not be converted to `<` and `>`

### ISSUE THREAD

**Issue by karelbilek** [JohannesKaufmann/html-to-markdown#30]
**Describe the bug**

`&lt;` and `&gt;` should not be converted to `<` and `>`, it breaks the resulting markdown.

**HTML Input**
```html
&lt;not a tag&gt;
```

**Generated Markdown**
````markdown
<not a tag>
````

**Expected Markdown**
````markdown
&lt;not a tag&gt;
````

**Additional context**
Markdown parsers take `<not a tag>` as a tag and do not show it. That's not what is in the HTML though.

Example: https://spec.commonmark.org/dingus/?text=%3Cnot%20a%20tag%3E%0A%0A%26lt%3Bsecond%26gt%3B

**Comment by JohannesKaufmann** [comment]
@karelbilek  Hmm, it’s the same behaviour that [turndown](http://domchristie.github.io/turndown/) is doing.

I can’t do much about it right now, it is either `goquery` or `net/html` that seems to be doing it. 

You could try to do `html.EscapeString(markdown)` on the final markdown output (or override the “#text” rule). Although that will also escape other characters, which might not be what you want.

I can look into this again next week, right now I’m just too busy 🤷‍♂️

**Comment by karelbilek** [comment]
It's reported an issue in turndown at least 2 times, it seems 😃 

https://github.com/domchristie/turndown/issues/261
https://github.com/domchristie/turndown/issues/106

**Comment by karelbilek** [comment]
> You could try to do html.EscapeString(markdown) on the final markdown output (or override the “#text” rule).

It will need to be on #text somewhere; cannot do it on all the output, as that would break code. That is. HTML input

```
<pre>&lt;foo&gt;</pre>
```

should have output

    `<foo>`

But 

```
&lt;foo&gt;
```

should have (identical) output

```
&lt;foo&gt;
```

**Comment by hilmanski** [comment]
Hi any update or new solution for this issue?
