### ISSUE TITLE
Incorrect coding of `<code><...></code>`

### ISSUE THREAD

**Issue by inliquid** [JohannesKaufmann/html-to-markdown#35]
**HTML Input**
```html
<code>
<a href="#Blabla">
	<img src="http://bla.bla/img/img.svg" style="height:auto" width="200px"/>
</a>
</code>
```

**Generated Markdown**
````markdown
 `



`
````

**Expected Markdown**
````markdown
```
<a href="#Blabla">
	<img src="http://bla.bla/img/img.svg" style="height:auto" width="200px"/>
</a>
```
````

**Comment by JohannesKaufmann** [comment]
@inliquid thanks for submitting the bug. Just fixed the bug that the html tags inside are not displayed.

-----

But if you want a code block (\`\`\`) and not inline code (\`) you need to put a `pre` tag around the  the `code` tag.


> Use \<code> for inline code that can **wrap** and \<pre>\<code> for block code that **must not wrap**.
https://stackoverflow.com/a/4611735
