### ISSUE TITLE
Nested lists aren't converted correctly

### ISSUE THREAD

**Issue by dmorrison-olive** [JohannesKaufmann/html-to-markdown#37]
**Describe the bug**
I'm seeing a problem converting nested HTML lists. The problem appears with either ordered (`<ol>`) or unordered (`<ul>`) lists.

**HTML Input**
```html
<ol>
	<li>One</li>
	<ol>
		<li>One point one</li>
		<li>One point two</li>
	</ol>
</ol>
```

**Generated Markdown**
````markdown
1. One

1. One point one
2. One point two
````

**Expected Markdown**
````markdown
1. One
    1. One point one
    2. One point two
````

**Additional context**
I see this with the latest version (1.2.1). I'm using the following test code to check this:

```go
package main

import (
	"fmt"
	"log"

	md "github.com/JohannesKaufmann/html-to-markdown"
)

func main() {
	converter := md.NewConverter("", true, nil)

	html := `
<ol>
	<li>One</li>
	<ol>
		<li>One point one</li>
		<li>One point two</li>
	</ol>
</ol>
`

	markdown, err := converter.ConvertString(html)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("md ->\n%s\n", markdown)
}

```

Thanks for the library!

**Comment by dmorrison-olive** [comment]
For anyone else wondering how to work around this, I (temporarily?) switched to using [godown](https://github.com/mattn/godown).

**Comment by JohannesKaufmann** [comment]
@dmorrison-olive thanks for reporting this 🎉

I now have a fix that works a lot better with nested lists. But still need to work on a few details and on cleaning up. So expect a new version in the next couple of days...

**Comment by JohannesKaufmann** [comment]
@dmorrison-olive you can now download the new version (v1.3.0) by running `go get github.com/JohannesKaufmann/html-to-markdown@v1.3.0`.

Please let me know if you find any other bugs 🙏

**Comment by dmorrison-olive** [comment]
Thanks for the quick update! Seems to work now. 👍
