### ISSUE TITLE
Extra <span> elements in <code> blocks

### ISSUE THREAD

**Issue by mbrt** [JohannesKaufmann/html-to-markdown#41]
Some websites use `<code>` blocks with `<span>` elements inside. It seems to be the case when the syntax highlighting is computed server-side, rather than on the browser with some JS library such as [prettify](https://github.com/googlearchive/code-prettify).

To reproduce:

```go
func main() {
	converter := md.NewConverter("", true, nil)
	url := "https://atomizedobjects.com/blog/javascript/how-to-get-the-last-segment-of-a-url-in-javascript"
	markdown, _ := converter.ConvertURL(url)
	fmt.Println("markdown)
}
```

What I get (scrolling down a bit):

```
``js
window<span class="token punctuation">.</span>location<span class="token punctuation">.</span>pathname<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">"/"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token parameter">entry</span> <span class="token operator">=></span> entry <span class="token operator">!==</span> <span class="token string">""</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// ["blog", "javascript", "how-to-get-the-last-segment-of-a-url-in-javascript"]</span>
``
```

What you get if you just remove all `<span>` elements from the generated markdown:

```
window.location.pathname.split("/").filter(entry => entry !== "");
// ["blog", "javascript", "how-to-get-the-last-segment-of-a-url-in-javascript"]
```

I know that an easy workaround on my side would be to just clean things up with `goquery`, but I figured it would be better to have it fixed here directly.

Thanks!

**Comment by JohannesKaufmann** [comment]
@mbrt yeah you are totally right, that is a bit annoying. 

I will definitely fix that at some point. Unfortunately, quite busy right now due to University 🙈

**Comment by JohannesKaufmann** [comment]
@mbrt I released a new version that tries to work with highlighted code blocks. Let me know if you encounter any problems...

**Comment by mbrt** [comment]
It looks great now! Thanks!
