### ISSUE TITLE
Brackets escaping is currently disabled

### ISSUE THREAD

**Issue by wcalandro** [JohannesKaufmann/html-to-markdown#42]
**Describe the bug**
Brackets are currently not being escaped by html-to-markdown

**HTML Input**
```html
[this should be escaped](http://test)
```

**Generated Markdown**
````markdown
[this should be escaped](http://test)
````

**Expected Markdown**
````markdown
\[this should be escaped\](http://test)
````

**Additional context**
What would it take for the bracket escaping to be re-enabled in `escape.go`? I see that it was previously disabled due to issues with the regex. Does it simply require a more robust regular expression?

**Comment by JohannesKaufmann** [comment]
@wcalandro yeah you are totally correct, I disabled this regex because of an issue.

But just fixed it and released a new version. Thanks for reporting it 👍
