### ISSUE TITLE
🐛 Spaces missing before em elements

### ISSUE THREAD

**Issue by dlrice** [JohannesKaufmann/html-to-markdown#43]
**Describe the bug**
Spaces missing before `em` elements

**HTML Input**
```html
<ul style="list-style-type:disc">
    <li>All manually reviewed <em>Drosophila melanogaster</em> entries</li>
    <li>All manually reviewed <em>Drosophila pseudoobscura pseudoobscura</em> entries</li>
</ul>
```

**Generated Markdown**
````markdown
- All manually reviewed_Drosophila melanogaster_ entries
- All manually reviewed_Drosophila pseudoobscura pseudoobscura_ entries
````

**Expected Markdown**
````markdown
- All manually reviewed _Drosophila melanogaster_ entries
- All manually reviewed _Drosophila pseudoobscura pseudoobscura_ entries
````

**Additional context**
Also seeing this with the `GitHubFlavored` plugin.

P.S. Thanks a lot for the developing this package - it's very handy!

**Comment by JohannesKaufmann** [comment]
@dlrice thanks for reporting 🎉

Fixed this and released a new version. 

Please let me know if you catch any other bugs...
