### ISSUE TITLE
[Feature Request] a switch to enable preserve html comments in markdown

### ISSUE THREAD

**Issue by anig1scur** [JohannesKaufmann/html-to-markdown#46]
Some times we need `<!-- cmts-->` to keep more information

For example, html file is
```html
<p><!--any comments-->sample markdown.</p>

<h2 id="subsub-SecondHeading">Second Heading</h2>

```

Then, markdown file is
```md
<!--any comments-->sample markdown.

## Second Heading
```

Many thanks!

**Comment by JohannesKaufmann** [comment]
@anig1scur you can add a custom rule yourself:


```
commentRule := md.Rule{
	Filter: []string{"#comment"},
	Replacement: func(content string, selec *goquery.Selection, opt *md.Options) *string {
		data := selec.Nodes[0].Data

		return md.String(" <!-- " + data + " --> ")
	},
}

conv := md.NewConverter("", true, nil)
conv.AddRules(commentRule)
```

The variable `selec` is the goquery selection, which is a helpful abstraction over the `golang.org/x/net/html` package. With `selec.Nodes[0]` you are accessing the underlying data structure. The comment data is stored in `Data`, in this case its "any comments".

Hope that helps!

**Comment by JohannesKaufmann** [comment]
@anig1scur actually even simpler! You can tell it to keep this element by writing

```go
conv := md.NewConverter("", true, nil)
conv.Keep("#comment")
```
