### ISSUE TITLE
🐛 Bug: code tag nested inside pre tag is not recognized

### ISSUE THREAD

**Issue by zhang19523zhao** [JohannesKaufmann/html-to-markdown#47]
![image](https://user-images.githubusercontent.com/77541540/162349951-27c5a4ea-e82e-4337-b0f3-d68802fd0ba0.png)
![image](https://user-images.githubusercontent.com/77541540/162350032-32e52ab2-db3a-4bf3-abee-8047cc575633.png)
![image](https://user-images.githubusercontent.com/77541540/162350100-81b0561e-e3e8-4db3-b5f2-9ced49cb97c6.png)

This code doesn't seem to work

**Comment by zhang19523zhao** [comment]
Thanks♪(･ω･)ﾉ

**Comment by k1ng440** [comment]
Hi, is there any update?

**Comment by JohannesKaufmann** [comment]
@k1ng440 unfortunately it turns out to be trickier than I thought. Especially since people use pre/code tags very differently. So this is going to take some time unfortunately...

**Comment by JohannesKaufmann** [comment]
@zhang19523zhao @k1ng440 This should now be fixed in the latest version. Please let me know if you find any code snippets that don't work as expected.

Make sure to update the library by running:
```
go get -u github.com/JohannesKaufmann/html-to-markdown
```
