### ISSUE TITLE
🐛 Bug: Support `<tt>` for code next to `<code>` tags

### ISSUE THREAD

**Issue by ljrk0** [JohannesKaufmann/html-to-markdown#49]
**Describe the bug**
Unfortunately, some sites don't use semantic markup, e.g.,
http://math.andrej.com/2007/09/28/seemingly-impossible-functional-programs/
but instead specify the font directly using `tt`.  Since markdown draws no distinction b/w code and things simply formatted in "typewriter style", these should be recognized at well (or, at least, as a plugin).

**HTML Input**
```html
<tt>Some typewriter text</tt>
```

**Generated Markdown**
````markdown
Some typewriter text
````

**Expected Markdown**
````markdown
`Some typewriter text`
````

**Additional context**
N/A

**Comment by JohannesKaufmann** [comment]
Yeah, good catch. It's probably a good idea to add support for other HTML tags. In addition to [`<tt>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt) for example also `<kbd>`, `<samp>` and `<var>`. 



Should be a pretty easy addition to the library... I will also add a test-case with that snippet for `<tt>` from the website that you shared.

If you find any other tags on other websites, let me know. It's always good to have a wide variety of snippets for the tests...

**Comment by ljrk0** [comment]
Yeah, it should mostly be about adding it to the Filter expression AFAICT.

I'm currently using the linked lapwat/papeer to load all longer articles I want to read onto my e reader, so I'm sure to stumble upon other missing tags :-)

I've went ahead and added an issue tracking MathJax although that is a bit more complicated:
https://github.com/JohannesKaufmann/html-to-markdown/issues/50

**Comment by JohannesKaufmann** [comment]
This should now be fixed in the latest version.

Make sure to update the library by running:
```
go get -u github.com/JohannesKaufmann/html-to-markdown
```

If you encounter any other bugs, feel free to open a new issue...
