### ISSUE TITLE
Potential issue in the Table plugin with the isFirstTbody logic

### ISSUE THREAD

**Issue by bramstes** [JohannesKaufmann/html-to-markdown#55]
Hello in the table.go plugin there's an issue with the firstSibling logic in the isFirstTbody function.

func isFirstTbody(s *goquery.Selection) bool {
	firstSibling := s.Siblings().Eq(0) // TODO: previousSibling
	if s.Is("tbody") && firstSibling.Length() == 0 {
		return true
	}
	return false
}

I'm retrieving tables from confluence html format tbody-tr-th's. Somehow the firstSibling.Length() is not 0 haven't figured it out completely but when I comment it out it seems to do what it's supposed to do although might introduce a new bug :).

github.com/JohannesKaufmann/html-to-markdown v1.3.6
github.com/PuerkitoBio/goquery v1.8.0

**Comment by JohannesKaufmann** [comment]
@bramstes can you please add the HTML snippet that causes the problems?

And you are using commonmark + the table plugin? Any other plugin?

**Comment by JohannesKaufmann** [comment]
[**#event\_1**\
\
**01.01.2023**](/)
---

* Coffee
* Tea

  * Black tea
  * Green tea
* Milk

---


* Coffee
* Tea
  X
  * Black tea
  * Green tea
  
  Y
* Milk

---

1. Metro Court West.
2. Richie General.

   1. This place is ok.
   2. Watch out for the doctors.
      1. They bite.
      2. But not hard.

---

1. Metro Court West.
2. Richie General.
3.
   1. This place is ok.
   2. Watch out for the doctors.
   3.
      1. They bite.
      2. But not hard.
