### ISSUE TITLE
Configure elements to keep in `<code>`

### ISSUE THREAD

**Issue by zrcoder** [JohannesKaufmann/html-to-markdown#57]
**Describe the bug**

**HTML Input**
```html
<p>The ordinal number "fifth" can be abbreviated in various languages as follows:</p>
<ul>
	<li><code>English: 5<sup>th</sup></code></li>
	<li>French: 5<sup>ème</sup></li>
</ul>
```

**Generated Markdown**
````markdown
The ordinal number "fifth" can be abbreviated in various languages as follows:

- `English: 5th`
- French: 5<sup>ème</sup>
````

**Expected Markdown**
````markdown
The ordinal number "fifth" can be abbreviated in various languages as follows:

- `English: 5<sup>th</sup>`
- French: 5<sup>ème</sup>
````

**Additional context**
I use `NewConverter("", true, nil).Keep("sup")` to convert.

**Comment by JohannesKaufmann** [comment]
Here is what the HTML would be displayed in the browser:

<img width="283" alt="Screenshot 2022-12-30 at 13 02 42" src="https://user-images.githubusercontent.com/20886667/210068295-d7bbb8cd-27b0-4cbd-8109-d0cf307679a2.png">

The markdown representation `` `English: 5th` `` would render ` English: 5th `,
while the markdown representation `` `English: 5<sup>th</sup>` `` would render `English: 5<sup>th</sup>`.

As such, the current implementation is closest to what the browser would display.

---

The `Keep()` function is for normal HTML elements, not for elements _inside_ a code block. So for example, for keeping a `<sup>` element inside a paragraph.

If many people need it, one could add something like a `KeepInsideCode` function. But not planned for now...

---

@zrcoder If you want something different than the [current implementation](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/commonmark.go#L296-L327), you can [write your own rule](https://github.com/JohannesKaufmann/html-to-markdown/blob/master/examples/add_rules/main.go). Let me know if you encounter any problems with this...
