### ISSUE TITLE
The YoutubeEmbed Plugin

### ISSUE THREAD

**Issue by suntong** [JohannesKaufmann/html-to-markdown#65]
How to use the YoutubeEmbed Plugin pls?

This, 

https://github.com/JohannesKaufmann/html-to-markdown/blob/8eb812b8869e447bb712afdb05d8627da816ecae/plugin/youtube.go#L16

unlike other plugins, is a `var` instead of a function. Would you,

- change it to a normal function, and
- remove the `EXPERIMENTAL` part from its name please?

Ref, the request is coming from https://github.com/suntong/html2md/issues/7

thanks

**Comment by JohannesKaufmann** [comment]
With the version `1.5.0` I made the iframe plugins easier to use. I considered them experimental because I am not *actively using* these two plugins. So I don't know how well they work over many websites 🤷‍♂️
