### ISSUE TITLE
🐛 Bug? <br> turns one line break into two

### ISSUE THREAD

**Issue by suntong** [JohannesKaufmann/html-to-markdown#66]
**Describe the bug**
A clear and concise description of what the bug is --
`<br>` turns one line break into two.

**HTML Input**
```html
foo<br>bar
```

**Generated Markdown**
````markdown
foo

bar
````

**Expected Markdown**
````markdown
foo
bar
````

**Additional context**

The problem was initially reported at https://github.com/suntong/html2md/issues/15

**Comment by JohannesKaufmann** [comment]
duplicate of #40
