### ISSUE TITLE
Is there a way to export the out to a md file directly?

### ISSUE THREAD

**Issue by zenminimalist** [JohannesKaufmann/html-to-markdown#72]
Is there a way for the code to save the output into a md file instead of having the md output in the terminal? So example.html would automate be save as example.md

And ideally it would work for directories or multiple files. Any way to achieve that now or would this have to be added as a feature?

**Comment by JohannesKaufmann** [comment]
Hi @zenminimalist 

sorry, somehow I completely missed the notification for your comment.

There is a cool library called „io/ioutil“ which you could use to achieve this result.

For example, with `ioutil.ReadDir()` you could get all the files inside a directory.

Feel free to open a PR to add this as an example to the examples folder.

**Comment by zenminimalist** [comment]
Thanks, no worries. I'm not a coder myself (unfortunately), I can't utilize the library. Also, I've never opened a PR. Hence, I'm not sure which options to select or how that works without causing additional work for you. But I'm happy to learn how to open a PR and what that actually means :)

**Comment by JohannesKaufmann** [comment]
@zenminimalist since you are not a coder, it might be best if you use the [CLI](https://github.com/suntong/html2md#usage) instead of the Golang Library
