### ISSUE TITLE
can‘t convert table in html to markdown

### ISSUE THREAD

**Issue by xiongjinchao** [JohannesKaufmann/html-to-markdown#8]
can‘t convert table in html to markdown

**Comment by xiongjinchao** [comment]
import "github.com/JohannesKaufmann/html-to-markdown/plugin"
converter.Use(plugin.GitHubFlavored())

it work well, except the table container the character “|”

**Comment by JohannesKaufmann** [comment]
@xiongjinchao this should be fixed now. 

Sorry, I forgot about this repository 🙈
