### ISSUE TITLE
🐛 Bug - Basic escape slashes innocent vertical pipes

### ISSUE THREAD

**Issue by acook** [JohannesKaufmann/html-to-markdown#86]
Vertical pipe characters are escaped no matter where they are in the line even though most (all?) markdown parsers don't treat this case specially. 

I'm not sure if there are some parsers which treat any pipe as a table, if so then maybe a new escape mode is needed? But if not, then it should be possible to only escape pipes at the beginning of the line.

**HTML Input**
```html
Foo | Bar
```

**Generated Markdown**
````markdown
Foo \| Bar
````

**Expected Markdown**
````markdown
Foo | Bar
````

**Additional context**

- https://github.com/suntong/html2md v1.1.2

**Comment by JohannesKaufmann** [comment]
@acook yeah you are totally right! It would be great if the pipe character would be omitted in this case. 

But with the "basic" escaping that is just not possible at the moment 🤷‍♂️

---

For V2 there will be a "smart" escaping. But that requires implementing some logic of a markdown **parser**. So basically we would ***only*** escape if it would _actually_ be mistaken by a parser.

**Comment by acook** [comment]
The more I thought about it the more I realized that if the parser is very straight forward and efficient then it probably wouldn't have a concept of state for more than duplicates, so it might require some effort to rework. 

Looking at the code now my first impression is that it kind of doing `tr` style escaping, and you're right, a more robust parser would be needed to handle these weird edge cases. 

While I don't necessarily *recommend* this approach, it would be possible to set a flag by checking for a match for a pattern of pipe characters so that various table formats would be respected.

```go
r := regexp.MustCompile("\|.*\n.*\|")
is_table := r.MatchString(cursor_at_current_line

if is_table {
  // do normal escaping
}
```

Using this basic test case, the first entry is *not* matched but the second and third are, meaning that it should be safe from escaping. There might be issues with other table formats, but this is a start, regardless of what eventual approach there might be!

```
Foo | Bar

Foo | Bar
---|---

|Foo | Bar
|---|---
```

**Comment by JohannesKaufmann** [comment]
On the ["v2" branch](https://github.com/JohannesKaufmann/html-to-markdown/tree/v2) are a lot of improvements — including a much better logic for escaping markdown characters.

It is still experimental but feel free to give it a try. Happy to hear about your experience 😊

I am going to close this issue. If you find anything with the new version, please open a new issue!
