### ISSUE TITLE
When converting the html of the li tag, the newline character is lost

### ISSUE THREAD

**Issue by lansemei** [JohannesKaufmann/html-to-markdown#88]
**Describe the bug**

**HTML Input**
```html
<ol>
                    <li>第1.1.1行第2次按tab</li>
                    <li>第1.1.2行第2次按tab</li>
                </ol>
```

**Generated Markdown**
````markdown
第1.1.1行第2次按tab第1.1.2行第2次按tab
````

**Expected Markdown**
````markdown
第1.1.1行第2次按tab
第1.1.2行第2次按tab
````

**Additional context**
When converting the html of the li tag, the newline character is lost. Even if you forcefully add\ n, it will be lost when converting again

**Comment by JohannesKaufmann** [comment]
@lansemei can you check the "HTML Input" in your Github Comment? Unfortunately I cannot reproduce this bug
