### ISSUE TITLE
Has the program stopped maintenance?

### ISSUE THREAD

**Issue by qianniancn** [JohannesKaufmann/html-to-markdown#98]
The program hasn't been maintained for a long time, did it stop?

**Comment by JohannesKaufmann** [comment]
It is still maintained. The current version _works well enough_ — but some edge-cases are difficult with the current architecture.

At the moment I am working on version 2 of the library. It hopefully fixes all the problems. But is not ready yet...

**Comment by qianniancn** [comment]
Ok, looking forward to the v2 version
